<?xml version="1.0" encoding="utf-8"?><Database Name="DoctorAppointment" Class="AppointmentClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=DoctorAppointment;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DoctorAppointmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AppointmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartsFrom" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EndTo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DoctorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>