//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionMedicine
    {
        public int PrescribedMedicineID { get; set; }
        public string Medicine { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public string Frequency { get; set; }
    }
}
